package com.iquest.advancedframeworks.internetbanking.controllers.configuration.springsecurity;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SecurityWebApplicationInitializer extends AbstractSecurityWebApplicationInitializer {

}
